-- MySQL Script generated by MySQL Workbench
-- Tue Apr 25 17:08:40 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema henriquemattos_vworders
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `vworders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vworders` ;

CREATE TABLE IF NOT EXISTS `vworders` (
  `vworders_id` INT NOT NULL AUTO_INCREMENT,
  `vworders_order` VARCHAR(45) NULL,
  `vworders_date` DATE NULL,
  `vworders_client` VARCHAR(255) NULL,
  `vworders_cpf_cnpj` VARCHAR(45) NULL,
  `vworders_zip` VARCHAR(45) NULL,
  `vworders_address` VARCHAR(255) NULL,
  `vworders_email` VARCHAR(255) NULL,
  `vworders_phone` VARCHAR(45) NULL,
  `vworders_mobile` VARCHAR(45) NULL,
  `vworders_print_color` VARCHAR(45) NULL,
  `vworders_delivery_date` VARCHAR(45) NULL,
  `vworders_extras_costs` VARCHAR(45) NULL,
  `vworders_delivery_price` VARCHAR(45) NULL,
  `vworders_total` VARCHAR(45) NULL,
  `vworders_payment_days` VARCHAR(45) NULL,
  `vworders_payment_method` VARCHAR(45) NULL,
  `vworders_payment_value` VARCHAR(45) NULL,
  `vworders_obs` VARCHAR(45) NULL,
  PRIMARY KEY (`vworders_id`),
  UNIQUE INDEX `id_UNIQUE` (`vworders_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vworders_products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vworders_products` ;

CREATE TABLE IF NOT EXISTS `vworders_products` (
  `vworders_product_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `vworders_product_color` VARCHAR(45) NULL,
  `vworders_product_amount` VARCHAR(45) NULL,
  `vworders_product_unit` VARCHAR(45) NULL,
  `vworders_product_total` VARCHAR(45) NULL,
  `vworders_products_type` VARCHAR(45) NULL,
  `vworders_vworders_id` INT NOT NULL,
  PRIMARY KEY (`vworders_product_id`, `vworders_vworders_id`),
  UNIQUE INDEX `vworders_product_id_UNIQUE` (`vworders_product_id` ASC),
  INDEX `fk_vworders_products_vworders_idx` (`vworders_vworders_id` ASC),
  CONSTRAINT `fk_vworders_products_vworders`
    FOREIGN KEY (`vworders_vworders_id`)
    REFERENCES `vworders` (`vworders_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
